name: mosquito_alert_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.17.1
  flutter_cupertino_localizations: ^1.0.1
  webview_flutter: ^0.3.19+9
  google_maps_flutter: ^0.5.27
  material_segmented_control: ^2.0.10
  camera: ^0.5.7+4
  path_provider: ^1.6.5
  path: ^1.6.4
  uuid: ^2.0.4
  shared_preferences: ^0.5.6+3
  http: ^0.12.0+2
  random_string: ^2.0.1
  geolocator: ^5.3.1
  dio: ^3.0.9
  image_picker: ^0.6.5+2
  firebase_core: ^0.4.4+3
  firebase_analytics: ^5.0.11
  firebase_messaging: ^6.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

  assets:
   - assets/img/
   - assets/
  #  - images/a_dot_ham.jpeg

 
  
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

