name: mosquito_alert_app
description: A new Flutter project.

version: 0.9+115

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.17.4
  flutter_cupertino_localizations: ^1.0.1
  webview_flutter: ^0.3.19+9
  google_maps_flutter: ^0.5.28+1
  material_segmented_control: ^2.0.10
  path_provider: ^1.6.5
  path: ^1.6.4
  uuid: ^2.0.4
  shared_preferences: ^0.5.6+3
  http: ^0.12.0+2
  random_string: ^2.0.1
  geolocator: ^5.3.1
  dio: ^3.0.9
  image_picker: ^0.6.7+1
  firebase_auth: ^0.16.1
  firebase_messaging: ^6.0.16
  google_sign_in: ^4.4.4
  flutter_facebook_login: ^3.0.0
  auto_size_text: ^2.1.0
  file_picker: ^1.10.0
  geocoder: ^0.2.1
  device_info: ^0.4.2+4
  package_info: ^0.4.1
  flutter_launcher_icons: ^0.7.5
  url_launcher: ^5.2.5
  photo_view: ^0.9.2
  percent_indicator: ^2.1.5
  flutter_twitter: ^1.1.3
  flutter_widget_from_html_core: ^0.4.1
  geohash: ^0.2.1
  flutter_background_geolocation: ^1.9.2
  intro_slider: ^2.3.1
  flutter_material_pickers: ^1.7.1
  permission_handler: ^5.0.1+1
  language_pickers: ^0.2.0+1
  connectivity: ^0.4.9+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    

flutter_icons:
  image_path_android: "assets/img/ic_launcher.png"
  image_path_ios: "assets/img/ic_launcher.png"
  android: true
  ios: true


flutter:

  uses-material-design: true

  assets:
 
   - assets/
   - assets/img/
   - assets/img/maps/
   - assets/img/gallery/
   - assets/img/tutorial/
   - assets/language/
   - assets/html/

  
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
 

